/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_it.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Interrupt Service Routine
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
/********************Includes************************************************************************/
#include "SC_it.h"
#include "sc32_conf.h"
#include "stdio.h"
#include "HeadFiles\SC_itExtern.h"
#include "SCDriver_List.h"

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/

void INT0_IRQHandler(void)
{
  /*INT0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT0Interrupt Flag Clear end*/
}

void INT1_7_IRQHandler(void)
{
  /*INT1_7_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT1_7_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT1_7Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT1_7Interrupt Flag Clear end*/
}

void INT8_11_IRQHandler(void)
{
  /*INT8_11_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT8_11_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT8_11Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT8_11Interrupt Flag Clear end*/
}

void INT12_15_IRQHandler(void)
{
  /*INT12_15_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT12_15_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT12_15Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT12_15Interrupt Flag Clear end*/
}

void RCC_IRQHandler(void)
{
  /*RCC_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*RCC_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*RCCInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*RCCInterrupt Flag Clear end*/
}


void UART1_IRQHandler(void)
{
  /*UART1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART1Interrupt Flag Clear end*/
}

#if !defined (TK_USE_UART1_3)
void UART1_3_IRQHandler(void)
{
  /*UART1_3__it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3__it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART1_3_Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3_Interrupt Flag Clear end*/
}
#endif

#if !defined (TK_USE_UART1_3_5)
void UART1_3_5_IRQHandler(void)
{
  /*UART1_3_5_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3_5_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART1_3_5Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3_5Interrupt Flag Clear end*/
}
#endif

#if !defined (TK_USE_UART0_2)	
void UART0_2_IRQHandler(void)
{
  /*UART0_2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART0_2_Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2_Interrupt Flag Clear end*/
}
#endif

#if !defined (TK_USE_UART0_2_4)
void UART0_2_4_IRQHandler(void)
{
  /*UART0_2_4_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2_4_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART0_2_4_Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2_4_Interrupt Flag Clear end*/
}
#endif


#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void)
{
  /*BTM_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*BTM_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*BTMInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*BTMInterrupt Flag Clear end*/
}
#endif

void DMA0_IRQHandler(void)
{
  /*DMA0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*DMA0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA0Interrupt Flag Clear end*/
}

void DMA1_IRQHandler(void)
{
  /*DMA1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*DMA1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1Interrupt Flag Clear end*/
}


void DMA2_IRQHandler(void)
{
  /*DMA1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*DMA1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1Interrupt Flag Clear end*/
}

void DMA3_IRQHandler(void)
{
  /*DMA1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*DMA1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1Interrupt Flag Clear end*/
}


void TIMER0_IRQHandler(void)
{
  /*TIM0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER0Interrupt Flag Clear end*/
}

void TIMER1_IRQHandler(void)
{
  /*TIM1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER1Interrupt Flag Clear end*/
}

void TIMER2_IRQHandler(void)
{
  /*TIM2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM2_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER2Interrupt Flag Clear end*/
}

void TIMER3_IRQHandler(void)
{
  /*TIM3_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM3_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER3Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER3Interrupt Flag Clear end*/
}


void TIMER4_5_IRQHandler(void)
{
  /*TIM4_5_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM4_5_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER4_5Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER4_5Interrupt Flag Clear end*/
}

void TIMER6_7_IRQHandler(void)
{
  /*TIM6_7_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM6_7_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER6_7Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER6_7Interrupt Flag Clear end*/
}



void QEP0_IRQHandler(void)
{
  /*QEP0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*QEP0_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*QEP0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*QEP0Interrupt Flag Clear end*/
}

void QEP1_IRQHandler(void)
{
  /*QEP1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*QEP1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*QEP1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*QEP1Interrupt Flag Clear end*/
}

void OP1_OP2_IRQHandler(void)
{
  /*OP1_OP2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*OP1_OP2_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*OP1_OP2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*OP1_OP2Interrupt Flag Clear end*/
}

void SPI1_TWI1_IRQHandler(void)
{
  /*SPI1_TWI1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1_TWI1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SPI1_TWI1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1_TWI1Interrupt Flag Clear end*/
}

void CAN_IRQHandler(void)
{
  /*CAN_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CAN_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*CANInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CANInterrupt Flag Clear end*/
}

void EPWM_IRQHandler(void)
{
  /*EPWM_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*EPWM_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*EPWMInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*EPWMInterrupt Flag Clear end*/
}

void PCAP_IRQHandler(void)
{
  /*PCAP_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*PCAP_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*PCAPInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*PCAPInterrupt Flag Clear end*/
}


void TWI0_IRQHandler(void)
{
  /*TWI0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TWI0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TWI0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TWI0Interrupt Flag Clear end*/
}

void TWI1_IRQHandler(void)
{
  /*TWI1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TWI1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TWI1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TWI1Interrupt Flag Clear end*/
}

void PWM0_IRQHandler(void)
{
  /*PWM0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*PWM0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*PWM0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*PWM0Interrupt Flag Clear end*/
}

void LEDPWM_IRQHandler(void)
{
  /*LEDPWM_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*LEDPWM_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*LEDPWMInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*LEDPWMInterrupt Flag Clear end*/
}

void ADC_IRQHandler(void)
{
  /*ADC_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*ADC_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*ADCInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*ADCInterrupt Flag Clear end*/
}

void CMP0_1_2_IRQHandler(void)
{
  /*CMP0_1_2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CMP0_1_2_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*CMP0_1_2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CMP0_1_2Interrupt Flag Clear end*/
}

void CMP3_IRQHandler(void)
{
  /*CMP3_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CMP3_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*CMP3Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CMP3Interrupt Flag Clear end*/
}

void CMP_IRQHandler(void)
{
  /*CMP_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CMP_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*CMPInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CMPInterrupt Flag Clear end*/
}


void SysTick_IRQHandler(void)
{
  /*SysTick_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SysTick_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SysTickInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SysTickInterrupt Flag Clear end*/
}

void SPI0_IRQHandler(void)
{
  /*SPI0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SPI0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI0Interrupt Flag Clear end*/
}

void SPI1_IRQHandler(void)
{
  /*SPI1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SPI1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1Interrupt Flag Clear end*/
}

void SPI1_2_IRQHandler(void)
{
  /*SPI1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SPI1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1Interrupt Flag Clear end*/
}
