/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!! 
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}































