/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         main.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its H file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
/*******************Includes************************************************************************/

#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
#include "FreeRTOS.h"
#include "task.h"
#include "DMA_Circular_Buffer.h"
#include "SPI_Chunk_Buffer.h"
#include "print.h"

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/

static TaskHandle_t tasks[3];

void vTask_Monitor(void *pvParameters) {
	for(;;) {
        print(temp, "Monitor", PRINT_LEVEL_0, "free heap", xPortGetMinimumEverFreeHeapSize(), "bytes");
        print(temp, pcTaskGetName(tasks[0]), PRINT_LEVEL_0, "free stack", uxTaskGetStackHighWaterMark(tasks[0]), "words");
        print(temp, pcTaskGetName(tasks[1]), PRINT_LEVEL_0, "free stack", uxTaskGetStackHighWaterMark(tasks[1]), "words");
        GPIO_TogglePins(GPIOB, GPIO_Pin_15);
	    vTaskDelay(1000);
	}
}

uint8_t test[8] = {1,2,3,4,5,6,7,8};
void vTask_SPI(void *pvParameters) {
	for(;;) {
        print(temp, "SPI", PRINT_LEVEL_0, "free stack", uxTaskGetStackHighWaterMark(NULL), "words");
	    vTaskDelay(250);
        //SPI_Send_One(&spi0, 88);
        SPI_Send_Multi(&spi0, test, 8);
	}
}

/**
  * @brief This function implements main function.
  * @note 
  * @param
  */
int main(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<UserCodeStart>*//*<SinOne-Tag><36>*/
    
    IcResourceInit();
    DMA_Circular_Buffer_Init();
    SPI_ChunkBuffer_Init(&spi0);

    /*<UserCodeEnd>*//*<SinOne-Tag><36>*/
    /*<UserCodeStart>*//*<SinOne-Tag><4>*/

    xTaskCreate(vTask_Monitor, "Monitor", 72, NULL, 1, &tasks[0]);
    xTaskCreate(vTask_DMA_Circular_Buffer, "DMA_Circular_Buffer", 48, NULL, 2, &tasks[1]);
    xTaskCreate(vTask_SPI, "SPI", 64, NULL, 3, &tasks[2]);
    vTaskStartScheduler();
    
    /*****MainLoop*****/
    while(1) {
        /*<UserCodeStart>*//*<SinOne-Tag><14>*/
        /***User program***/
        /*<UserCodeEnd>*//*<SinOne-Tag><14>*/
        /*<Begin-Inserted by EasyCodeCube for Condition>*/
    }
    /*<UserCodeEnd>*//*<SinOne-Tag><4>*/
    /*<Generated by EasyCodeCube end>*/
}
