/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_it.c
  * @author
  * @version
  * @date
  * @brief
  * @details         Interrupt Service Routine
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
/********************Includes************************************************************************/

#include "SC_it.h"
#include "sc32_conf.h"
#include "stdio.h"
#include "HeadFiles\SC_itExtern.h"
#include "SCDriver_List.h"
#include "DMA_Circular_Buffer.h"

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/

void INT0_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void INT1_7_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void INT8_11_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void INT12_15_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void RCC_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}


void UART1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

#if !defined (TK_USE_UART1_3)
void UART1_3_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
#endif

#if !defined (TK_USE_UART1_3_5)
void UART1_3_5_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
	UART_ClearFlag(UART1,UART_Flag_RX | UART_Flag_TX);//Generated by EasyCodeCube, forbid editing!!!
}
#endif

#if !defined (TK_USE_UART0_2)
void UART0_2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
#endif

#if !defined (TK_USE_UART0_2_4)
void UART0_2_4_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
#endif


#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
#endif

void DMA0_IRQHandler(void)
{
	DMA_ClearFlag(DMA0, DMA_FLAG_GIF|DMA_FLAG_TCIF|DMA_FLAG_HTIF|DMA_FLAG_TEIF);//Generated by EasyCodeCube, forbid editing!!!
    DMA_Circular_Buffer_IRQHandler();
}

/*
void DMA1_IRQHandler(void)
{
	DMA_ClearFlag(DMA1, DMA_FLAG_GIF|DMA_FLAG_TCIF|DMA_FLAG_HTIF|DMA_FLAG_TEIF);//Generated by EasyCodeCube, forbid editing!!!
}
*/

void DMA2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void DMA3_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}


void TIMER0_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void TIMER1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void TIMER2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void TIMER3_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}


void TIMER4_5_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void TIMER6_7_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}



void QEP0_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void QEP1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void OP1_OP2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void SPI1_TWI1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void CAN_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void EPWM_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void PCAP_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}


void TWI0_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void TWI1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void PWM0_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void LEDPWM_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void ADC_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void CMP0_1_2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void CMP3_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void CMP_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/*
void SPI0_IRQHandler(void)
{
	SPI_ClearFlag(SPI0, SPI_Flag_SPIF|SPI_Flag_RINEIF|SPI_Flag_TXEIF|SPI_Flag_RXFIF|SPI_Flag_RXHIF|SPI_Flag_TXHIF|SPI_Flag_WCOL);//Generated by EasyCodeCube, forbid editing!!!
}
*/

void SPI1_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

void SPI1_2_IRQHandler(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
