/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_UART1_Init();
	SC_DMA0_Init();
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(DISABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_HIRCDIV1Cmd(ENABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(8000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PB15 Struct*/GPIO_InitTypeDef GPIOInit_PB15_Struct;
	GPIOInit_PB15_Struct.GPIO_Pin = GPIO_Pin_15;
	GPIOInit_PB15_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB15_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB15_Struct);/*PB.15端口初始化*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PB01 Struct*/GPIO_InitTypeDef GPIOInit_PB01_Struct;
	GPIOInit_PB01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PB01_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PB01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB01_Struct);/*TxD1端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_UART1, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 64000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART1, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART1,UART_IT_EN,DISABLE);
	/*DMA_TX*/UART_DMACmd(UART1,UART_DMAReq_TX,ENABLE);
	/*DMA_RX*/UART_DMACmd(UART1,UART_DMAReq_RX,DISABLE);
	/*Init Struct*/UART_PinRemapConfig(UART1,UART_PinRemap_Default);
	UART_TXCmd(UART1,ENABLE);
	UART_RXCmd(UART1,DISABLE);
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA,ENABLE);
	/*Init Struct*/DMA_InitTypeDef DMA_InitStruct;
	DMA_InitStruct.DMA_Priority = DMA_Priority_LOW;
	DMA_InitStruct.DMA_TargetMode = DMA_TargetMode_FIXED;
	DMA_InitStruct.DMA_SourceMode = DMA_SourceMode_INC_CIRC;
	DMA_InitStruct.DMA_SrcAddress = 0x0000;
	DMA_InitStruct.DMA_DstAddress = 0x0000;
	DMA_InitStruct.DMA_DataSize = DMA_DataSize_Byte;
	DMA_InitStruct.DMA_Burst = DMA_Burst_Disable;
	DMA_InitStruct.DMA_Request = DMA_Request_UART1_TX;
	DMA_InitStruct.DMA_BufferSize = 0x0000;
	DMA_InitStruct.DMA_CircularMode = DMA_CircularMode_Disable;
	DMA_Init(DMA0, &DMA_InitStruct);
	/*INTEN*/DMA_ITConfig(DMA0,DMA_IT_INTEN, ENABLE);
	/*TEIE*/DMA_ITConfig(DMA0,DMA_IT_TEIE, DISABLE);
	/*HTIE*/DMA_ITConfig(DMA0,DMA_IT_HTIE, DISABLE);
	/*TCIE*/DMA_ITConfig(DMA0,DMA_IT_TCIE, ENABLE);
	DMA_DMACmd(DMA0,DMA_DMAReq_CHRQ,DISABLE);
	/*Init Struct*/NVIC_SetPriority(DMA0_IRQn,3);/*DMA0*/
	NVIC_EnableIRQ(DMA0_IRQn);
	DMA_Cmd(DMA0,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}































